# Generated by Django 5.1.1 on 2024-10-05 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_name', models.CharField(max_length=255)),
                ('flipkart_name', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=500)),
                ('amazon_url', models.URLField(max_length=500)),
                ('flipkart_url', models.URLField(max_length=500)),
                ('amazon_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flipkart_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='wishlisted_by', to='wishlist.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='login.customuser')),
            ],
        ),
    ]
