# Generated by Django 5.1.1 on 2024-10-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_product_color_product_ram_product_rom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCheckTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, unique=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
